Stage-2
StopTheClocks4ever/java-explore-with-me pull request #2
Opened 2024-06-08 20:33 UTC by StopTheClocks4ever

2024-06-09 20:37 UTC, mikita95 requested changes
Все сделано просто отлично :) Оставил лишь небольшую рекомендацию

2024-06-09 20:37 UTC, mikita95 commented on ewm-service/src/main/resources/schema.sql
> +    initiator_id BIGINT NOT NULL,
Можно было бы добавить индексы на колонки, по которым часто выполняются запросы, так было бы эффективнее при большом количестве данных

2024-06-09 20:57 UTC, StopTheClocks4ever commented on ewm-service/src/main/resources/schema.sql
> +    initiator_id BIGINT NOT NULL,
Сделал для таблиц Events и Requests, так как в них часто происходят обращения по внешним ключам

2024-06-11 11:27 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-06-11 17:43 UTC, merged